#cloud-config
package_update: true
package_upgrade: true

groups:
- docker

system_info:
  default_user:
    groups: [docker]

packages:
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
- docker-ce
- docker-ce-cli
- containerd.io
- unattended-upgrades
- jq

apt:
  sources:
    # https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/examples.html#additional-apt-configuration-and-repositories
    docker.list:
      # source
      # Creates a file in /etc/apt/sources.list.d/ for the sources list entry
      # based on the key: "/etc/apt/sources.list.d/docker.list"
      # One can specify [signed-by=$KEY_FILE] in the source definition, which
      # will make the key be installed in the directory /etc/cloud-init.gpg.d/
      # and the $KEY_FILE replacement variable will be replaced with the path
      # to the specified key. If $KEY_FILE is used, but no key is specified,
      # apt update will (rightfully) fail due to an invalid value.
      source: "deb [arch=amd64 signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu jammy stable"
      # keyid
      # Importing a gpg key for a given key id. Used keyserver defaults to
      # keyserver.ubuntu.com
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 # GPG key ID published on a key server

run-cmd:
- sysctl -w net.ipv4.ip_forward=1
- echo 1 > /proc/sys/net/ipv4/ip_forward
- echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
- sysctl -p /etc/sysctl.conf